version: "3.8"

services:
  frontend:
      container_name: frontend
      build:
        context: frontend
        dockerfile: Dockerfile
      volumes:
        - "./frontend/:/usr/app/"
        - "/usr/app/node_modules"
      ports:
        - "${FRONTEND_PORT}:5173"
      env_file:
        - .env
